backend:
  name: github # 如果代码托管在GitLab或Gitee，则相应修改为gitlab或gitee
  repo: 你的用户名/你的仓库名 # 例如：octocat/my-website
  branch: main # 或者 master

media_folder: "images/uploads" # 上传的图片会存到这里
public_folder: "/images/uploads" # 网站引用图片的路径

collections:
  - name: "pages" # 内容类型名称
    label: "页面" # 在后台显示的标签
    files:
      - label: "首页" # 在后台显示的页面名称
        name: "index" # 文件标识
        file: "index.html" # 要编辑的文件路径
        fields: # 定义页面上有哪些内容可以编辑
          - {label: "页面标题", name: "title", widget: "string"}
          - {label: "页面主体", name: "body", widget: "markdown"}